# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad19b5dacaa4f7d5cbd78f4f7ee7c61bc0b0523bc6135aeb7555770f333918424faaecaac1310586db2c66e72c094096ff8382a0a0f501c8fd1f24a28340682

test:
  secret_key_base: a8d4c07e12c3f4eaa3e74ab9bbbd59623c6a3b62b050f2ae4ff21a012695f56b0edba1338de2555da1d35b4e1787fe4d1229006f25b74ba203da222136e14137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
